{"run_number": "1736154088575028", "step_name": "cluster", "task_id": "3", "attempt_id": 0, "name": "_exception", "content_type": "gzip+pickle-v2", "type": "metaflow.artifact", "sha": "f3627f46179fdd95bf0e83101840fd1d71b60e40", "ds_type": "local", "location": ":root:/Users/hanin/ums-l200220272.github.io/.metaflow", "flow_id": "ManyKmeansFlow", "user_name": "hanin", "tags": [], "system_tags": ["runtime:dev", "user:hanin", "metaflow_version:2.12.39", "python_version:3.10.16"], "ts_epoch": 1736154092587}